title: <p align="center"> Mahesh Kumar Patra </p>
logo: /assets/img/Mahesh.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/mahesh-kumar-patra/">LinkedIn</a> |
  <a href="https://github.com/maheshkumarpatra">GitHub</a>
  
  <br>
  Being Flexible, Quick Learner and Adaptive, seeking for opportunities to enhance the knowledge 
  and skills as a performer and contribute in the growth of organization.Skilled at using statistics,
  machine learning techniques and visualization to build a competitive advantage.
  <br>
  </p>



theme: jekyll-theme-minimal
