title: <p align="center"> Mahesh Kumar Patra </p>
logo: /assets/img/Mahesh.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/mahesh-kumar-patra/">LinkedIn</a> |
  <a href="https://github.com/maheshkumarpatra">GitHub</a>



theme: jekyll-theme-minimal
